### ISSUE TITLE
How is this different from 'custom-react-scripts' ?

### ISSUE THREAD

**Issue by aligajani** [shrynx/react-super-scripts#8]

**Comment by shrynx** [comment]
@aligajani react-super-scripts have a few differences compared to custom-react-scripts major ones being
* Supports for webpack dashboard
* Customisable babel-config
*  Image compression
* Hot module reloading
* Preact support

You can check the readme for further details
[react-super-scripts](https://github.com/shrynx/react-super-scripts/blob/develop/README.md)
[custom-react-scripts](https://github.com/kitze/create-react-app/blob/master/README.md)

just try using both and choose whichever suits you.

**Comment by aligajani** [comment]
Great. What is your promise of future updates ?

**Comment by shrynx** [comment]
i maintain regular updates with create-react-app releases and use it at my work in production.

**Comment by aligajani** [comment]
Great. May I know what files have you added or modified from the original repository.
 Just for my knowledge.

**Comment by shrynx** [comment]
I try to hamper with create-react-app files as less as possible, for maintainability. Wepback config is modified at runtime with a helper utility (found in packages/react-scripts/utils/customWebpackConfig.js) and another utility is for reading react-super-scripts object from package.json. Apart from these there are some more tiny changes. you can explore them [here](https://github.com/shrynx/react-super-scripts/tree/develop/packages/react-scripts)

**Comment by aligajani** [comment]
@shrynx  thanks man. Great stuff. @kitze Do you also modify configs at runtime on your fork?

Also @shrynx , one more thing. How can I compare the differences between your fork and the original.

**Comment by shrynx** [comment]
You can check the commit history i suppose.
